name: Roger Hutchings - CV
markdown: redcarpet
pygments: true
exclude:
    - node_modules
    - bower_components
    - bower.json
    - config.rb
    - ftp.json
    - Gruntfile.js
    - package.json
    - README.md
baseurl: ''
environment: dev
